version: "3.8"
services:
  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports: -"3306:3306"
  be:
    build: ./be
    ports: -"8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: myapp
  fe:
    build: ./fe
    ports:
      - "3000:3000"
    depends_on:
      - be

volumes:
  db-data:
